-- MySQL Script generated by MySQL Workbench
-- Fri Apr 20 20:02:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `githubtracker` DEFAULT CHARACTER SET utf8 ;
USE `githubtracker` ;

-- -----------------------------------------------------
-- Table `mydb`.`githuber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `githubtracker`.`githuber` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `github_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `bio` LONGTEXT NULL,
  `location` VARCHAR(45) NULL,
  `avatar_url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
